# Generated by Django 6.0.4 on 2026-04-19 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cellules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cellule',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['responsable', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cellules_dirigees', to=settings.AUTH_USER_MODEL),
        ),
    ]
