# Generated by Django 6.0.4 on 2026-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellules', '0003_cellule_quartier_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellule',
            name='commune',
            field=models.CharField(blank=True, help_text='Ex: Tambacounda, Maka, Sainthiou Maleme', max_length=100),
        ),
        migrations.AddField(
            model_name='cellule',
            name='departement',
            field=models.CharField(default='Tambacounda', help_text='Département', max_length=100),
        ),
    ]
