# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellules', '0004_cellule_commune_cellule_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellule',
            name='couleur',
            field=models.CharField(default='#3B82F6', help_text='Couleur de la cellule au format hexadécimal (ex: #3B82F6)', max_length=7),
        ),
    ]
