# Generated by Django 6.0.4 on 2026-04-23 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellules', '0005_cellule_couleur'),
        ('membres', '0026_alter_membre_optin_pastef_infos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellule',
            name='commune',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cellule',
            name='couleur',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AlterField(
            model_name='cellule',
            name='departement',
            field=models.CharField(default='Tambacounda', max_length=100),
        ),
        migrations.AlterField(
            model_name='cellule',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False, 'role': 'responsable'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cellules_dirigees', to='membres.membre'),
        ),
    ]
