# Generated by Django 6.0.4 on 2026-04-19 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cellules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('quartier', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('militant', 'Militant'), ('responsable', 'Responsable')], default='militant', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cellule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='cellules.cellule')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'db_table': 'membres',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
