# Generated by Django 6.0.4 on 2026-04-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='bureau_vote',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membre',
            name='centre_vote',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_expiration_carte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='inscrit_liste_electorale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membre',
            name='numero_carte_electeur',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='membre',
            name='numero_identification',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='membre',
            name='optin_pastef_infos',
            field=models.BooleanField(default=False, verbose_name='Recevoir infos PASTEF/élections'),
        ),
    ]
