# Generated by Django 6.0.4 on 2026-04-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0003_membre_bureau_vote_membre_centre_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='bureau_vote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='centre_vote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
