# Generated by Django 6.0.4 on 2026-04-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0004_alter_membre_bureau_vote_alter_membre_centre_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='numero_carte_electeur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='numero_identification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
