# Generated by Django 6.0.4 on 2026-04-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0023_alter_membre_optin_pastef_infos'),
        ('membres', '0024_add_performance_indexes'),
    ]

    operations = [
    ]
