# Generated by Django 6.0.4 on 2026-04-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0025_merge_20260422_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='optin_pastef_infos',
            field=models.BooleanField(default=False, verbose_name='Recevoir infos PASTEF/élections'),
        ),
    ]
