# Generated by Django 6.0.4 on 2026-04-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimoVotant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=200)),
                ('annee_naissance', models.IntegerField()),
                ('telephone', models.CharField(max_length=20)),
                ('a_nin', models.BooleanField(default=False)),
                ('numero_nin', models.CharField(blank=True, max_length=50, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Primo Votant',
                'verbose_name_plural': 'Primo Votants',
                'db_table': 'primo_votants',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
