# Generated by Django 6.0.4 on 2026-04-25 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('a_venir', 'A venir'), ('en_cours', 'En cours'), ('termine', 'Termine'), ('annule', 'Annule')], default='a_venir', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activite',
                'verbose_name_plural': 'Activites',
                'db_table': 'activites',
                'ordering': ['-date_debut'],
            },
        ),
    ]
